# Generated by Django 3.2.15 on 2022-09-26 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iaaxblock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iaafeedback',
            name='id_stage',
        ),
        migrations.RemoveField(
            model_name='iaastage',
            name='id_activity',
        ),
        migrations.RemoveField(
            model_name='iaasubmission',
            name='id_stage',
        ),
        migrations.AddField(
            model_name='iaafeedback',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iaaxblock.iaastage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaastage',
            name='activity',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iaaxblock.iaaactivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iaasubmission',
            name='stage',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iaaxblock.iaastage'),
            preserve_default=False,
        ),
    ]
