# Generated by Django 3.2.16 on 2023-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iaaxblock', '0002_auto_20220926_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iaastage',
            name='stage_number',
            field=models.TextField(),
        ),
    ]
